# Generated by Django 3.1.4 on 2023-12-09 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='firstname',
            new_name='fname',
        ),
    ]
