# Generated by Django 3.2.23 on 2023-12-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_doctor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=2)),
                ('phoneNo', models.CharField(max_length=10)),
                ('appointmentDate', models.CharField(max_length=10)),
                ('symptoms', models.CharField(max_length=10)),
            ],
        ),
    ]
