# Generated by Django 3.2.23 on 2023-12-29 06:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_apps'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.RemoveField(
            model_name='apps',
            name='appointment',
        ),
        migrations.AddField(
            model_name='apps',
            name='appointmentDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
