# Generated by Django 3.2.23 on 2024-01-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_feed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitalinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalname', models.CharField(max_length=10)),
                ('doctorname', models.CharField(max_length=10)),
                ('specialization', models.CharField(max_length=10)),
                ('phonenumber', models.CharField(max_length=20)),
                ('area', models.TextField()),
                ('location', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
    ]
