# Generated by Django 3.2.23 on 2024-01-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_hospitalinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalinfo',
            name='doctorname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hospitalinfo',
            name='hospitalname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hospitalinfo',
            name='phonenumber',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hospitalinfo',
            name='specialization',
            field=models.CharField(max_length=50),
        ),
    ]
