# Generated by Django 3.2.23 on 2024-01-07 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_auto_20240107_1555'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
