# Generated by Django 3.2.23 on 2024-01-07 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_appointmentinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apps',
        ),
    ]
